# Generated by Django 2.2.6 on 2019-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='linkPortada',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
