# Generated by Django 2.2.6 on 2019-11-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0003_libro_linkportada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deseado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBookStore.Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBookStore.Usuario')),
            ],
        ),
    ]
