# Generated by Django 2.2.6 on 2019-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0004_deseado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha',
            field=models.IntegerField(default=0),
        ),
    ]
