# Generated by Django 2.2.6 on 2019-11-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0005_libro_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='destacado',
            field=models.IntegerField(default=0),
        ),
    ]
