# Generated by Django 2.2.6 on 2019-11-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0010_auto_20191115_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deseado',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBookStore.Libro'),
        ),
    ]
