# Generated by Django 2.2.6 on 2019-11-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0011_auto_20191115_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appBookStore.Idioma'),
        ),
        migrations.AddField(
            model_name='libro',
            name='promocionado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='ventas',
            field=models.IntegerField(default=0),
        ),
    ]
