# Generated by Django 2.2.6 on 2019-11-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0012_auto_20191115_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appBookStore.Idioma'),
        ),
    ]
