# Generated by Django 2.2.6 on 2019-11-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookStore', '0016_auto_20191115_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='sinopsis_max',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sinopsis_min',
            field=models.CharField(default='', max_length=200),
        ),
    ]
